# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# CNI plugin selector
# the possible values would be: "danm" or "multus"
cni: "multus"
#add before-hook-creation if want to delete the previous resource before a new hook is launched
#hook_delete_policy: "hook-failed,before-hook-creation"
hook_delete_policy: "hook-failed"

danm:
  # IP routes for all the danm networks will be installed in this routing table
  # MANDATORY - INTEGER (e.g. 100)
  rt_tables: 100

multus:
  whereabouts:
    # the logs would be written on k8s nodes in the absolute file name provided
    logFile: "/tmp/whereabouts.log"
    # the possible values would be "debug", "error" or "panic"
    logLevel: "error"

#worker node network interface
ldapLan:
  enabled: false
  name: ldap-lan
  interfaceName: ldapLan
  hostDevice: eno1.31
  type: dynamic
  cidr: 10.255.45.0/24
  allocationPoolStartIp: 10.255.45.85
  allocationPoolEndIp: 10.255.45.88
  routes:
    - dst: 10.9.227.0/24
      gw: 10.255.45.254
    - dst: 10.67.35.64/28
      gw: 10.255.45.254
    - dst: 10.67.26.0/24
      gw: 10.255.45.254
    - dst: 10.67.26.0/28
      gw: 10.255.45.254
    - dst: 10.9.230.0/24
      gw: 10.255.45.254
    - dst: 10.67.29.96/27
      gw: 10.255.45.254
    - dst: 10.91.34.0/24
      gw: 10.255.45.254
    - dst: 10.67.31.0/24
      gw: 10.255.45.254
    - dst: 10.255.35.0/24
      gw: 10.255.45.254
    - dst: 10.9.228.0/24
      gw: 10.255.45.254
    - dst: 10.255.34.0/24
      gw: 10.255.45.254
    - dst: 10.255.10.0/24
      gw: 10.255.45.254
    - dst: 10.255.9.0/24
      gw: 10.255.45.254
    - dst: 10.255.8.0/24
      gw: 10.255.45.254
   
#edge node network interface
ldaplbLan:
  enabled: true
  name: ldaplb-lan
  interfaceName: ldaplbLan
  hostDevice: eno1.31
  type: dynamic
  cidr: 10.255.45.0/24
  allocationPoolStartIp: 10.255.45.85
  allocationPoolEndIp: 10.255.45.88
  routes:
    - dst: 10.9.227.0/24
      gw: 10.255.45.254
    - dst: 10.67.35.64/28
      gw: 10.255.45.254
    - dst: 10.67.26.0/24
      gw: 10.255.45.254
    - dst: 10.67.26.0/28
      gw: 10.255.45.254
    - dst: 10.9.230.0/24
      gw: 10.255.45.254
    - dst: 10.67.29.96/27
      gw: 10.255.45.254
    - dst: 10.91.34.0/24
      gw: 10.255.45.254
    - dst: 10.67.31.0/24
      gw: 10.255.45.254
    - dst: 10.255.35.0/24
      gw: 10.255.45.254
    - dst: 10.9.228.0/24
      gw: 10.255.45.254
    - dst: 10.255.34.0/24
      gw: 10.255.45.254
    - dst: 10.255.10.0/24
      gw: 10.255.45.254
    - dst: 10.255.9.0/24
      gw: 10.255.45.254
    - dst: 10.255.8.0/24
      gw: 10.255.45.254
   
vnflbLan:
  enabled: false
  name: vnflb-lan
  interfaceName: vnflbLan
  hostDevice: eno1.36
  type: dynamic
  cidr: 10.255.46.128/27
  allocationPoolStartIp: 10.255.46.143
  allocationPoolEndIp: 10.255.46.144
  routes:
   - dst: 10.103.199.6/32
     gw: 10.93.16.1

diam1Lan:
  enabled: true
  name: diam1-lan
  interfaceName: diam1Lan
  hostDevice: eno1.31
  type: static
  cidr: 10.255.45.0/24
  allocationPoolStartIp: 10.255.45.153
  allocationPoolEndIp: 10.255.45.154
  routes:
    - dst: 10.67.34.200/32
      gw: 10.255.45.254
    - dst: 10.67.32.0/24
      gw: 10.255.45.254
    - dst: 10.67.35.36/32
      gw: 10.255.45.254
    - dst: 10.67.27.0/24
      gw: 10.255.45.254
    - dst: 10.67.28.0/24
      gw: 10.255.45.254
    - dst: 10.67.31.106/32
      gw: 10.255.45.254
    - dst: 10.255.22.163/32
      gw: 10.255.45.254
    - dst: 10.67.32.31/32
      gw: 10.255.45.254
    - dst: 10.255.32.19/32
      gw: 10.255.45.254

triggerLan:
  enabled: true
  name: trigger-lan
  interfaceName: triggerLan
  hostDevice: eno1.31
  type: dynamic
  cidr: 10.255.45.0/24
  allocationPoolStartIp: 10.255.45.25
  allocationPoolEndIp: 10.255.45.26
  routes:
    - dst: 10.9.227.0/24
      gw: 10.255.45.254
    - dst: 10.67.35.64/28
      gw: 10.255.45.254
    - dst: 10.67.26.0/24
      gw: 10.255.45.254
    - dst: 10.67.35.54/32
      gw: 10.255.45.254
    - dst: 10.67.35.57/32
      gw: 10.255.45.254
    - dst: 10.225.8.0/24
      gw: 10.255.45.254
    - dst: 10.67.27.0/24
      gw: 10.255.45.254
    - dst: 10.9.230.0/24
      gw: 10.255.45.254
    - dst: 10.67.32.32/32
      gw: 10.255.45.254
    - dst: 10.255.35.0/32
      gw: 10.255.45.254
    - dst: 10.9.228.0/24
      gw: 10.255.45.254
    - dst: 10.255.10.0/24
      gw: 10.255.45.254
    - dst: 10.67.35.71/32
      gw: 10.255.45.254
    - dst: 10.67.26.9/32
      gw: 10.255.45.254
    - dst: 10.67.26.0/28
      gw: 10.255.45.254
    - dst: 10.67.35.57/32
      gw: 10.255.45.254
    - dst: 10.9.227.0/24
      gw: 10.255.45.254

acreencryptLan:
  enabled: true
  name: acreencrypt-Lan
  interfaceName: acreencryptLan
  hostDevice: eno1.31
  type: dynamic
  cidr: 10.255.45.0/24
  allocationPoolStartIp: 10.255.45.27
  allocationPoolEndIp: 10.255.45.28
  routes:

http2lbLan:
  enabled: true
  name: http2lb-lan
  interfaceName: http2
  hostDevice: eno1.31
  type: static
  cidr: 10.255.45.0/24
  allocationPoolStartIp: 10.255.45.53
  allocationPoolEndIp: 10.255.45.54
  routes:
    - dst: 10.67.30.0/24
      gw: 10.255.45.254
    - dst: 10.67.35.120/29
      gw: 10.255.45.254
    - dst: 10.67.34.200/32
      gw: 10.255.45.254
    - dst: 10.67.33.32/32
      gw: 10.255.45.254
    - dst: 10.67.26.0/24
      gw: 10.255.45.254
    - dst: 10.67.27.0/24
      gw: 10.255.45.254
    - dst: 10.67.31.0/24
      gw: 10.255.45.254
    - dst: 10.255.50.0/24
      gw: 10.255.45.254
    - dst: 10.67.35.33/32
      gw: 10.255.45.254

liLan:
  enabled: true
  name: li-lan
  interfaceName: liLan
  hostDevice: eno1.31
  type: dynamic
  cidr: 10.255.45.0/24
  allocationPoolStartIp: 10.255.45.113
  allocationPoolEndIp: 10.255.45.114
  routes:
    - dst: 10.67.32.0/24
      gw: 10.255.45.254
    - dst: 10.67.27.0/24
      gw: 10.255.45.254
    - dst: 10.67.28.0/32
      gw: 10.255.45.254
    - dst: 10.67.35.120/29
      gw: 10.255.45.254

hsm1Lan:
  enabled: true
  name: hsm1-lan
  interfaceName: hsm1Lan
  hostDevice: eno1.31
  type: dynamic
  cidr: 10.255.45.0/24
  allocationPoolStartIp: 10.255.45.133
  allocationPoolEndIp: 10.255.45.134
  routes:
    - dst: 10.9.230.0/24
      gw: 10.255.45.254
    - dst: 10.9.226.0/24
      gw: 10.255.45.254

hsm2Lan:
  enabled: true
  name: hsm2-lan
  interfaceName: hsm2Lan
  hostDevice: eno1.32
  type: dynamic
  cidr: 10.255.46.0/25
  allocationPoolStartIp:  10.255.46.13
  allocationPoolEndIp:  10.255.46.14
  routes:

diam2Lan:
  enabled: true
  name: diam2-lan
  interfaceName: diam2Lan
  hostDevice: eno1.32
  type: static
  cidr: 10.255.46.0/25
  allocationPoolStartIp: 10.255.46.33
  allocationPoolEndIp: 10.255.46.34
  routes:

diammh1Lan:
  enabled: false
  name: diammh1-lan
  interfaceName: diammh1Lan
  hostDevice: eno1.31
  type: static
  cidr: 10.255.45.0/24
  allocationPoolStartIp: 10.255.45.173
  allocationPoolEndIp: 10.255.45.174
  routes:
   - dst: 10.103.194.2/32
     gw: 10.92.64.1

diammh2Lan:
  enabled: false
  name: diammh2-lan
  interfaceName: diammh2Lan
  hostDevice: eno1.32
  type: static
  cidr: 10.255.46.0/25
  allocationPoolStartIp: 10.255.46.53
  allocationPoolEndIp: 10.255.46.54
  routes:
   - dst: 10.103.195.2/32
     gw: 10.10.176.1

sigpLanhlr:
  enabled: true
  name: sigp-lan-hlr
  interfaceName: sigpLanhlr
  hostDevice: eno1.31
  type: static
  cidr: 10.255.45.0/24
  allocationPoolStartIp: 10.255.45.233
  allocationPoolEndIp: 10.255.45.234
  routes:
    - dst: 10.67.32.0/24
      gw: 10.255.45.254
    - dst: 10.67.35.120/29
      gw: 10.255.45.254
    - dst: 10.67.27.47/32
      gw: 10.255.45.254
    - dst: 10.67.27.176/32
      gw: 10.255.45.254
    - dst: 10.67.27.170/32
      gw: 10.255.45.254
   
sigsLanhlr:
  enabled: true
  name: sigs-lan-hlr
  interfaceName: sigsLanhlr
  hostDevice: eno1.32
  type: static
  cidr: 10.255.46.0/25
  allocationPoolStartIp: 10.255.46.93
  allocationPoolEndIp: 10.255.46.94
  routes:

InterCE1Lanhlr:
  enabled: true
  name: interce1-lan-hlr
  interfaceName: InterCE1Lanhlr
  hostDevice: eno1.31
  type: static
  cidr: 10.255.45.0/24
  allocationPoolStartIp: 10.255.45.193
  allocationPoolEndIp: 10.255.45.194
  routes:
    - dst: 10.255.45.193/32
      gw: 10.255.45.254
    - dst: 10.255.45.194/32
      gw: 10.255.45.254
 
InterCE2Lanhlr:
  enabled: true
  name: interce2-lan-hlr
  interfaceName: InterCE2Lanhlr
  hostDevice: eno1.31
  type: static
  cidr: 10.255.45.0/24
  allocationPoolStartIp: 10.255.45.213
  allocationPoolEndIp: 10.255.45.214
  routes:
    - dst: 10.255.45.213/32
      gw: 10.255.45.254
    - dst: 10.255.45.214/32
      gw: 10.255.45.254
  
InterCE3Lanhlr:
  enabled: true
  name: interce3-lan-hlr
  interfaceName: InterCE3Lanhlr
  hostDevice: eno1.32
  type: static
  cidr: 10.255.46.0/25
  allocationPoolStartIp: 10.255.46.73
  allocationPoolEndIp: 10.255.46.74
  routes:
    - dst: 10.255.46.73/32
      gw: 10.255.46.126
    - dst: 10.255.46.74/32
      gw: 10.255.46.126
